### ISSUE TITLE
symbol look up error while using the lammps executable

### ISSUE THREAD

**Issue by mm21d013** [materialsvirtuallab/matgl#321]
### Email (Optional)

mm21d013@smail.iitm.ac.in

### Version

v0.7.1

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### What happened?

 /home/pradeep/.local/bin/lmp: symbol lookup error: /home/pradeep/.local/bin/lmp: undefined symbol: _ZTIN3fmt6v9_lmp12format_errorE

I encounter this after I do make install. All the dependancies are installed however this error pops up whenever I try to check the lammps version or have to use the lmp executable

how to resolve this error?

### Code snippet

```python
/home/pradeep/.local/bin/lmp: symbol lookup error: /home/pradeep/.local/bin/lmp: undefined symbol: _ZTIN3fmt6v9_lmp12format_errorE
```

### Log output

```shell
/home/pradeep/.local/bin/lmp: symbol lookup error: /home/pradeep/.local/bin/lmp: undefined symbol: _ZTIN3fmt6v9_lmp12format_errorE
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kenko911** [comment]
Hi @mm21d013, please try to clean up your environment and install the latest version of MatGL then following our example of installing LAMMPS and running the simple simulation.

**Comment by mm21d013** [comment]
I have already developed a potential with 0.7.1 version. Upgrading to the latest version (v1.1.3) could potentially cause compatibility issues or require significant modifications to your existing work.Isn't it possible to do lammps calculations with the v0.7.1 version?
The matgl version kind of keeps updating almost every 2-3 weeks.

**Comment by kenko911** [comment]
I think LAMMPS doesn't support 0.7.1 and you may use ASE interface instead or the latest version of MatGL. I strongly recommend retraining the model with the latest version of MatGL since we fixed some crucial bugs in MatGL (please see our changelogs).

**Comment by mm21d013** [comment]
Even after installation in a new environment with v1.1.3 and creating an lmp executable with the example for lammps given in the github page...the information about lmp isn't showing up:

lmp -h command shows:

lmp: symbol lookup error: lmp: undefined symbol: _ZTIN3fmt6v9_lmp12format_errorE

I even did make clean following make install but the error persists

**Comment by kenko911** [comment]
Unfortunately, I am unable to reproduce your errors and this problem comes from LAMMPS side. please try ASE instead.

**Comment by mm21d013** [comment]
Can ASE interface with lammps....is there any documentation on how to use it to utilize the m3gnet potential for molecular dynamics simulations.

**Comment by kenko911** [comment]
It seems that you are new in the field and I would suggest you go through Atomistic Simulation Environment (ASE) and LAMMPS documentation to see the difference between them. You can go through our examples from the repo and they do show you how to run MD simulations using ASE.

**Comment by mm21d013** [comment]
ok...I will. Thanks. 

Just a clarification...I know how to execute an elastic constants calculations using LAMMPs. Can I do the same with ASE environment also?
Can a variable temperature molecular dynamics simulations be done with ASE?

**Comment by kenko911** [comment]
I think you can use MatCalc (https://github.com/materialsvirtuallab/matcalc) to calculate the elastic constants. Please refer to the ASE documentation for more details on variable temperature molecular dynamics simulations.

**Comment by mm21d013** [comment]
Thanks for your assistance.

**Comment by mm21d013** [comment]
Can you assist me on how to calculate stresses from the pymatgen structures using the m3gnet framework. Can you please guide me the location to calculate the stresses?

**Comment by kenko911** [comment]
Hi @mm21d013, please follow the examples from our repo. We use PESCalculater to calculate energies, forces and stresses via ASE interface. All you need to do is to read ASE documentation.
